In [7]:
from numpy import *
from scipy.ndimage import median_filter

The description of how the scipy median filter is not clear how the filter size works. Specifically, is it a radius or diameter?  To verify that I will first experiment with some specific examples.

In [8]:
t = arange(81.0)
t.shape = (9, 9)
print(t)
print("")
tm = median_filter(t, size=3, mode='constant', cval = 0.0)
print(tm)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23. 24. 25. 26.]
 [27. 28. 29. 30. 31. 32. 33. 34. 35.]
 [36. 37. 38. 39. 40. 41. 42. 43. 44.]
 [45. 46. 47. 48. 49. 50. 51. 52. 53.]
 [54. 55. 56. 57. 58. 59. 60. 61. 62.]
 [63. 64. 65. 66. 67. 68. 69. 70. 71.]
 [72. 73. 74. 75. 76. 77. 78. 79. 80.]]

[[ 0.  1.  2.  3.  4.  5.  6.  7.  0.]
 [ 1. 10. 11. 12. 13. 14. 15. 16.  8.]
 [10. 19. 20. 21. 22. 23. 24. 25. 17.]
 [19. 28. 29. 30. 31. 32. 33. 34. 26.]
 [28. 37. 38. 39. 40. 41. 42. 43. 35.]
 [37. 46. 47. 48. 49. 50. 51. 52. 44.]
 [46. 55. 56. 57. 58. 59. 60. 61. 53.]
 [55. 64. 65. 66. 67. 68. 69. 70. 62.]
 [ 0. 64. 65. 66. 67. 68. 69. 70.  0.]]


If the size is a diameter, that is a 3x3 region with the pixel of interest at the center, then the elements input into the 1,1 median location are 0.  1.  2.  9. 10. 11. 18. 19. 20. which has a median of 10

for the 8,8 location the inputs are 60. 61. 62. 69. 70. 71. 78. 79. 80. which has a median of 70

If the size is a radius such that elements contributing to the median are a 7x7 region then the 4,4 median location would have inputs of 

In [9]:
v = [0.,  1.,  2.,  3.,  4.,  5.,  6., 9., 10., 11., 12., 13., 14., 15., 18., 19., 20., 21., 22., 23., 24., 27., 28., 29., 30., 31., 32., 33., 36., 37., 38., 39., 40., 41., 42., 45., 46., 47., 48., 49., 50., 51., 54., 55., 56., 57., 58., 59., 60.,]
median(v)

30.0