# Example usage of the matplotlib mgrid and ogrid functions

In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


# 2D arrays

First, consider 2D arrays.  If we have a 2D function sampled uniformly on a 0.5 unit grid over the range of $x = [0, x_{sup})$, and $y = [0, y_{sup})$, with $x_{sup} = 4$ and $y_{sup} = 3$, this results in a $6x8$ matrix of sample values. If we want to calculate the $x$ and $y$ locations for each sample in the matrix we can use _mgrid_ in the following manner

In [29]:
step = 0.5
x_sup = 4
y_sup = 3
mg = mgrid[0:y_sup:step, 0:x_sup:step]
print(mg.shape)

(2, 6, 8)


.

The $y$ locations are returned in the first plane

In [15]:
mg[0, :, :]

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
       [2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. ],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

, and are changing with the row index of the matrix.  The $x$ locations are returned in the second plane

In [16]:
mg[1, :, :]

array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5]])

and are changing with column index of the matrix.

In both cases the size of the location matrices is the same as the size of the sampled function.  If we want to know the sample position of the element at $i_y = 4$ and $j_x$ = 6, we would use

In [12]:
print(mg[0, 4, 6])
print(mg[1, 4, 6])

2.0
3.0


.
# 3D arrays

Now, let's extend the problem to 3 dimensions by adding a third dimension $z = [0:z_{sup}), z_{sup} = 2$ to the function being sampled.



In [30]:
z_sup = 2
mg = mgrid[0:z_sup:step, 0:y_sup:step, 0:x_sup:step]
print(mg.shape)

(3, 4, 6, 8)


Now the $z$ locations are stored in the first ndarray (volume)

In [31]:
mg[0, :, :, :]

array([[[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]],

       [[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]],

       [[1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ]],

       [[1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 

, and are changing with the plannar index of the 3D array.  The $y$ locations are returned in the second ndarray (volume)

In [32]:
mg[1, :, :, :]

array([[[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        [2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. ],
        [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]],

       [[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        [2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. ],
        [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]],

       [[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
        [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
        [2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. ],
        [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]],

       [[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 

, and are changing with the row index of the 3D array.  The $x$ locations are returned in the last ndarray (volume)

In [33]:
mg[2, :, :, :]

array([[[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5]],

       [[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5]],

       [[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5]],

       [[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 

and are changing with column index of each plane within the ndarray (volume).

TODO: 
* describe the ogrid and nd_grid
* describe the effect of using a complex number as the last argument to specify the number of elements in each dimension instead of the step size (similar to using linspace)