This document is a basic exploration of several tomographic reconstruction techniques implemented using linear algebraic approaches.  A simplified underdetermined problem is explored. The volume to be reconstructed is a 2 row by 5 column uniform grid.  Starting with the simplest case, two orthogonal parallel beam projections.  The first in the +Y direction, through the 5 columns, the second in +X direction through the two rows 

In [1]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


Define the linear attenuation coefficient $\mu$ of the *volume*

In [22]:
n_rows = 2
n_columns = 5
mu = matrix(np.arange(n_rows * n_columns))
mu.shape = (n_rows, n_columns)
print(mu)

[[0 1 2 3 4]
 [5 6 7 8 9]]


We need to reshape $\mu$ intp a column vector so that it fits into the system of equations

In [26]:
mu.shape = (n_rows * n_columns, 1)
print(mu)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Define the forward operator A, that relates the linear attenuation coefficient to the detector responses.  The 5 row elements

In [30]:
A = matrix([[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], 
            [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
            [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0],
            [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0],
            [1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0]])

d = A * mu
print(d)

[[  5.]
 [  7.]
 [  9.]
 [ 11.]
 [ 13.]
 [ 13.]
 [ 10.]
 [ 35.]]


Simple backprojection of the volume is given by the equation $\mu_{est} = A^T d$

In [29]:
mu_est = A.transpose().dot(d)
mu_est.shape = (2, 5)
print(mu_est)

[[ 15.  17.  19.  21.  36.]
 [ 40.  42.  44.  46.  61.]]
